spring:
  cloud:
    stream:
      default-binder: solace_cloud
      bindings:
        join_request:
          destination: JOIN-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        gamestart_request:
          destination: GAMESTART-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        board_set_request:
          destination: BOARD-SET-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        move_request:
          destination: MOVE-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        tile_select_request:
          destination: TILE-SELECT-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        nextnumber_choose_request:
          destination: NEXTNUMBER-CHOOSE-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        nextnumber_confirm_request:
          destination: NEXTNUMBER-CONFIRM-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        prize_submit_request:
          destination: PRIZE-SUBMIT-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        player_page_request:
          destination: PLAYER-PAGE-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        admin_page_request:
          destination: ADMIN-PAGE-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        admin_landingpage_request:
          destination: ADMIN-LANDINGPAGE-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud  
        lobby_page_request:
          destination: LOBBY-PAGE-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        session_create_request:
          destination: SESSION-CREATE-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        session_search_request:
          destination: SESSION-SEARCH-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        prizemode_on_request:
          destination: PRIZEMODE-ON-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        prizemode_off_request:
          destination: PRIZEMODE-OFF-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
        prize_override_request:
          destination: PRIZE-OVERRIDE-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solace_cloud
      binders:
        solace_cloud:
          type: solace
          environment:
            solace:
              java:
                connectRetries: 3
                connectRetriesPerHost: 0
                reconnectRetries: 3
      solace:
        bindings:
          join_request:
            consumer:
              #Subscription for the join request queue
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/JOIN-REQUEST/*
          gamestart_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/GAMESTART-REQUEST
          board_set_request:
            consumer:
              #Subscription for the board set request queue
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/BOARD-SET-REQUEST/*
          move_request:
            consumer:
              #Subscription for the move request queue
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/MOVE-REQUEST/*
          tile_select_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/TILE-SELECT-REQUEST/*
          nextnumber_choose_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/NEXTNUMBER-CHOOSE-REQUEST
          nextnumber_confirm_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/NEXTNUMBER-CONFIRM-REQUEST
          prize_submit_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/PRIZE-SUBMIT-REQUEST/*
          player_page_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/PLAYER-PAGE-REQUEST/*
          admin_page_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/ADMIN-PAGE-REQUEST
          admin_landingpage_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/ADMIN-LANDINGPAGE-REQUEST
          lobby_page_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/LOBBY-PAGE-REQUEST
          session_create_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/SESSION-CREATE-REQUEST
          session_search_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/SESSION-SEARCH-REQUEST
          prizemode_on_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/PRIZEMODE-ON-REQUEST
          prizemode_off_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/PRIZEMODE-OFF-REQUEST
          prize_override_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/PRIZE-OVERRIDE-REQUEST
logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO

server:
  port: 8094
